#!/usr/bin/env bash

# Initialization
set -e -a
userDir=$PWD

cd "$(dirname "$0")"
source common/config.sh
source common/saving.sh
source common/validation.sh

# Make sure everything is properly configured
ensureConfigured

cat $CLIPBOARD_PATH/copy | while read line
do
    lineInput=(${line//,/ })
    from="${lineInput[0]}/${lineInput[1]}"
    to="${userDir}/${lineInput[1]}"
    cp -r $from $to 
done


cat $CLIPBOARD_PATH/cut | while read line
do
    lineInput=(${line//,/ })
    from="${lineInput[0]}/${lineInput[1]}"
    to="${userDir}/${lineInput[1]}"
    mv -r $from $to 
done

bash ctclean

echo "Done"